spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
